<?php

require_once __DIR__ . '/../models/databases.php';

$glasses = [
  [
    "id" => 1,
    "name" => "Alan",
    "brand" => "Brett",
    "price" => "120",
    "color" => "noir",
    "image_path" => "/../assets/img/marques/brett/lunettes/optiques/hommes/Alan-Brett.webp",
    "matter" => "titane",
    "gender" => "homme",
    "shape" => "pantos",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 2,
    "name" => "Peter",
    "brand" => "Brett",
    "price" => "150",
    "color" => "noir",
    "image_path" => "/../assets/img/marques/brett/lunettes/optiques/hommes/Peter-Brett.webp",
    "matter" => "Acetate",
    "gender" => "homme",
    "shape" => "carrée",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 3,
    "name" => "BIG Miles",
    "brand" => "Brett",
    "price" => "140",
    "color" => "bleu",
    "image_path" => "/../assets/img/marques/brett/lunettes/optiques/hommes/BIG-Miles-Brett.webp",
    "matter" => "acetate",
    "gender" => "homme",
    "shape" => "ronde",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 4,
    "name" => "Derek SUN",
    "brand" => "Brett",
    "price" => "250",
    "color" => "écaille",
    "image_path" => "/../assets/img/marques/brett/lunettes/solaires/hommes/Derek-SUN-Brett.webp",
    "matter" => "acétate",
    "gender" => "homme",
    "shape" => "carrée",
    "stock" => 1,
    "category" => "solaire",
    "image_name" => "name"
  ],
  [
    "id" => 5,
    "name" => "Ice",
    "brand" => "Bali",
    "price" => "200",
    "color" => "or",
    "image_path" => "/../assets/img/marques/Bali/lunettes/optiques/femmes/Ice-Bali.webp",
    "matter" => "métal",
    "gender" => "femme",
    "shape" => "octogonale",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 6,
    "name" => "Kahn",
    "brand" => "Bali",
    "price" => "199",
    "color" => "écaille",
    "image_path" => "/../assets/img/marques/Bali/lunettes/optiques/femmes/kahn_Bali.webp",
    "matter" => "acétate",
    "gender" => "femme",
    "shape" => "octogonale",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 7,
    "name" => "Jade",
    "brand" => "Bali",
    "price" => "189",
    "color" => "grise",
    "image_path" => "/../assets/img/marques/Bali/lunettes/optiques/femmes/jade-Bali.webp",
    "matter" => "acétate",
    "gender" => "femme",
    "shape" => "octogonale",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 8,
    "name" => "Jill SUN",
    "brand" => "Bali",
    "price" => "220",
    "color" => "écaille",
    "image_path" => "/../assets/img/marques/Bali/lunettes/solaires/femmes/jill-solaire_Bali.webp",
    "matter" => "acétate",
    "gender" => "femme",
    "shape" => "carrée",
    "stock" => 1,
    "category" => "solaire",
    "image_name" => "name"
  ],
  [
    "id" => 9,
    "name" => "Yukihime",
    "brand" => "Minamoto",
    "price" => "250",
    "color" => "Rouge",
    "image_path" => "/../assets/img/marques/Minamoto/lunettes/optiques/femmes/Yukihime-minamoto.png",
    "matter" => "Titane",
    "gender" => "femme",
    "shape" => "ronde",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 10,
    "name" => "Kyuzo",
    "brand" => "Minamoto",
    "price" => "290",
    "color" => "Gris",
    "image_path" => "/../assets/img/marques/Minamoto/lunettes/optiques/hommes/Kyuzo-minamoto.png",
    "matter" => "Titane",
    "gender" => "homme",
    "shape" => "Pantos",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],

  [
    "id" => 11,
    "name" => "Chisoku",
    "brand" => "Minamoto",
    "price" => "299",
    "color" => "Gris-noir",
    "image_path" => "/../assets/img/marques/Minamoto/lunettes/optiques/mixte/Chisoku-minamoto.png",
    "matter" => "Acétate et Titane",
    "gender" => "mixte",
    "shape" => "ronde",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 12,
    "name" => "Byoujou",
    "brand" => "Minamoto",
    "price" => "199",
    "color" => "Or rose",
    "image_path" => "/../assets/img/marques/Minamoto/lunettes/optiques/mixte/Byoujou-minamoto.png",
    "matter" => "Acétate",
    "gender" => "mixte",
    "shape" => "Carrée",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 13,
    "name" => "L'Hortensia",
    "brand" => "Paprika",
    "price" => "150",
    "color" => "Rose - Fushia",
    "image_path" => "/../assets/img/marques/Paprika/lunettes/optiques/femmes/Hortensia-Paprika.png",
    "matter" => "Acétate et Métal",
    "gender" => "femme",
    "shape" => "ronde",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 14,
    "name" => "Butterfly",
    "brand" => "Paprika",
    "price" => "180",
    "color" => "Vert et Marron",
    "image_path" => "/../assets/img/marques/Paprika/lunettes/optiques/femmes/Butterfly-Paprika.png",
    "matter" => "Acétate",
    "gender" => "femme",
    "shape" => "Ronde - Octogonale",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 15,
    "name" => "La Louve",
    "brand" => "Paprika",
    "price" => "160",
    "color" => "Or et noir",
    "image_path" => "/../assets/img/marques/Paprika/lunettes/optiques/femmes/La-Louve-Paprika.png",
    "matter" => "Métal et Acétate",
    "gender" => "femme",
    "shape" => "Héxagonale",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "name"
  ],
  [
    "id" => 16,
    "name" => "La Lucky",
    "brand" => "Clémence & Margaux",
    "price" => "140",
    "color" => "Bleu - Marron",
    "image_path" => "/../assets/img/marques/Clémence-&-Margaux/lunettes/solaires/femmes/Lucky-C&M.webp",
    "matter" => "Acétate - Métal",
    "gender" => "femme",
    "shape" => "Ronde",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "La Luck"
  ],
  [
    "id" => 17,
    "name" => "L'étudiante",
    "brand" => "Clémence & Margaux",
    "price" => "140",
    "color" => "Vert et Beige",
    "image_path" => "/../assets/img/marques/Clémence-&-Margaux/lunettes/solaires/femmes/étudiante-C&M.webp",
    "matter" => "Acétate",
    "gender" => "femme",
    "shape" => "Carrée",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "L'étudiante"
  ],
  [
    "id" => 18,
    "name" => "La Ziza",
    "brand" => "Clémence & Margaux",
    "price" => "160",
    "color" => "Noir",
    "image_path" => "/../assets/img/marques/Clémence-&-Margaux/lunettes/solaires/femmes/LA-Ziza-C&M.webp",
    "matter" => "Acétate",
    "gender" => "femme",
    "shape" => "Hexagonale",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "La Ziza"
  ],
  [
    "id" => 19,
    "name" => "Selma Kids",
    "brand" => "Bali",
    "price" => "130",
    "color" => "Bleu",
    "image_path" => "/../assets/img/marques/Bali/lunettes/optiques/enfants/selma-kids-Bali.webp",
    "matter" => "Acétate",
    "gender" => "enfant",
    "shape" => "Ronde",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "Selma Kids"
  ],
  [
    "id" => 20,
    "name" => "Jina Kids",
    "brand" => "Bali",
    "price" => "120",
    "color" => "Marron - Nude - Translucide",
    "image_path" => "/../assets/img/marques/Bali/lunettes/optiques/enfants/jina-kids-Bali.webp",
    "matter" => "Métal - Acétate",
    "gender" => "enfant",
    "shape" => "Carrée",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "Jina Kids"
  ],
  [
    "id" => 21,
    "name" => "MOD 1290",
    "brand" => "Cazal",
    "price" => 350,
    "color" => "Bleu nuit-or",
    "image_path" => "/../assets/img/marques/Cazal/lunettes/optiques/femmes/MOD1290-cazal.webp",
    "matter" => "Titane",
    "gender" => "femme",
    "shape" => "Papillon",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "MOD 1290"
  ],
  [
    "id" => 22,
    "name" => "MOD 226/3",
    "brand" => "Cazal",
    "price" => 450,
    "color" => "Gris dégradé",
    "image_path" => "/../assets/img/marques/Cazal/lunettes/solaires/femmes/MOD 226-3-cazal.webp",
    "matter" => "Acier inoxydable",
    "gender" => "femme",
    "shape" => "Originale",
    "stock" => 1,
    "category" => "solaire",
    "image_name" => "MOD 226/3"
  ],
  [
    "id" => 23,
    "name" => "MOD 7108",
    "brand" => "Cazal",
    "price" => 450,
    "color" => "Noir-or",
    "image_path" => "/../assets/img/marques/Cazal/lunettes/optiques/femmes/MOD 7108-cazal.webp",
    "matter" => "Titane",
    "gender" => "homme",
    "shape" => "Originale",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "MOD 7108"
  ],
  [
    "id" => 24,
    "name" => "MOD 7096",
    "brand" => "Cazal",
    "price" => 450,
    "color" => "Noir-argent",
    "image_path" => "/../assets/img/marques/Cazal/lunettes/optiques/hommes/MOD 7096-cazal.webp",
    "matter" => "Titane",
    "gender" => "homme",
    "shape" => "Originale",
    "stock" => 1,
    "category" => "optique",
    "image_name" => "MOD 7096"
  ],
  [
    "id" => 25,
    "name" => "MOD 9110",
    "brand" => "Cazal",
    "price" => 400,
    "color" => "Or",
    "image_path" => "/../assets/img/marques/Cazal/lunettes/solaires/hommes/MOD 9110-cazal.webp",
    "matter" => "Acier inoxydable",
    "gender" => "homme",
    "shape" => "Originale",
    "stock" => 1,
    "category" => "solaire",
    "image_name" => "MOD 7096"
  ],
  [
    "id" => 26,
    "name" => "MOD 8047",
    "brand" => "Cazal",
    "price" => 350,
    "color" => "cristal-or",
    "image_path" => "/../assets/img/marques/Cazal/lunettes/solaires/mixte/MOD 8047-cazal.webp",
    "matter" => "Acétate",
    "gender" => "mixte",
    "shape" => "Ronde",
    "stock" => 1,
    "category" => "solaire",
    "image_name" => "MOD 8047"
  ],
  [
    "id" => 27,
    "name" => "MOD 683",
    "brand" => "Cazal",
    "price" => 500,
    "color" => "noir-or",
    "image_path" => "/../assets/img/marques/Cazal/lunettes/solaires/hommes/MOD 683-cazal.webp",
    "matter" => "Acier inoxydable",
    "gender" => "homme",
    "shape" => "Pantos",
    "stock" => 1,
    "category" => "solaire",
    "image_name" => "MOD 683"
  ],
  [
    "id" => 28,
    "name" => "Exton",
    "brand" => "Andy Brook",
    "price" => 110,
    "color" => "Gris translucide",
    "image_path" => "/../assets/img/marques/Andy-brook/lunettes/solaires/Exton-Andybrook-enfant.jpg",
    "matter" => "Acétate",
    "gender" => "enfant",
    "shape" => "Carrée",
    "stock" => 1,
    "category" => "solaire",
    "image_name" => "Exton"
  ],
  [
    "id" => 29,
    "name" => "Peter",
    "brand" => "Andy Brook",
    "price" => 110,
    "color" => "Noir brillant / Extérieur branche translucide",
    "image_path" => "/../assets/img/marques/Andy-brook/lunettes/optiques/enfants/peter-andybrook.jpg",
    "matter" => "Acétate",
    "gender" => "enfant",
    "shape" => "Ronde",
    "stock" => 1,
    "category" => "solaire",
    "image_name" => "Peter"
  ],
  [
    "id" => 30,
    "name" => "Leo",
    "brand" => "Andy Brook",
    "price" => 110,
    "color" => "Noir brillant / Extérieur branche translucide",
    "image_path" => "/../assets/img/marques/Andy-brook/lunettes/optiques/enfants/leo-andybrook.jpg",
    "matter" => "Acétate",
    "gender" => "enfant",
    "shape" => "Ronde",
    "stock" => 1,
    "category" => "solaire",
    "image_name" => "Leo"
  ],
];

///////////////////////////////////////
// Insérer des lunettes dans la BDD //
/////////////////////////////////////

// foreach ($glasses as $glasse) {
//   $stmt = $pdo->prepare("INSERT INTO kghdsi_category (id, name, brand, price, color, image, matter, gender, shape, stock) VALUES (:id, :name, :brand, :price, :color, :image, :matter, :gender, :shape, :stock)");
//   $stmt->execute([
//     'id' => $glasse['id'],
//     'name' => $glasse['name'],
//     'brand' => $glasse['brand'],
//     'price' => $glasse['price'],
//     'color' => $glasse['color'],
//     'image' => $glasse['image'],
//     'matter' => $glasse['matter'],
//     'gender' => $glasse['gender'],
//     'shape' => $glasse['shape'],
//     'stock' => $glasse['stock'],
//     'category' => $glasse['optique'],
//   ]);
// }


?>


<!-- <form action="" method="POST">
    <label for="BDD">insertion BDD</label>
    <input type="text" name="BDD" id="BDD">
    <button type="submit"> inserer </button>
  </form> -->